import { mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { build } from 'esbuild'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const rootDir = join(scriptDir, '..')
const outputDir = join(rootDir, 'dist')
const outputFile = join(outputDir, 'index.js')

const unavailableOptionalNativeModule = {
  name: 'unavailable-optional-native-module',
  setup(context) {
    context.onResolve({ filter: /^cpu-features$/ }, () => ({
      path: 'cpu-features',
      namespace: 'dsh-remote-ssh-optional-native',
    }))
    context.onResolve({ filter: /sshcrypto\.node$/ }, () => ({
      path: 'sshcrypto.node',
      namespace: 'dsh-remote-ssh-optional-native',
    }))
    context.onLoad({ filter: /.*/, namespace: 'dsh-remote-ssh-optional-native' }, args => ({
      contents: `throw new Error(${JSON.stringify(`${args.path} is intentionally unavailable in the portable DSH Remote SSH bundle`)})`,
      loader: 'js',
    }))
  },
}

await mkdir(outputDir, { recursive: true })

const result = await build({
  entryPoints: [join(rootDir, 'src', 'index.js')],
  outfile: outputFile,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  legalComments: 'eof',
  logLevel: 'info',
  metafile: true,
  banner: {
    js: [
      "import { createRequire as __dshCreateRequire } from 'node:module';",
      "import { fileURLToPath as __dshFileURLToPath } from 'node:url';",
      "import { dirname as __dshDirname } from 'node:path';",
      'const require = __dshCreateRequire(import.meta.url);',
      'const __filename = __dshFileURLToPath(import.meta.url);',
      'const __dirname = __dshDirname(__filename);',
      '// Generated by scripts/build-host.mjs. Do not edit directly.',
    ].join('\n'),
  },
  external: [
    '@deepseek-ai/*',
  ],
  plugins: [unavailableOptionalNativeModule],
})

const output = result.metafile.outputs[outputFile.replaceAll('\\', '/')] || Object.values(result.metafile.outputs)[0]
const forbiddenRuntimeImports = (output?.imports || []).filter(item => (
  item.path === 'ssh2'
  || item.path === 'cpu-features'
  || item.path.endsWith('sshcrypto.node')
))

if (forbiddenRuntimeImports.length) {
  throw new Error(`Portable bundle still contains install-time SSH dependencies: ${forbiddenRuntimeImports.map(item => item.path).join(', ')}`)
}

const bundledInputs = Object.keys(result.metafile.inputs)
if (!bundledInputs.some(path => /[\\/]ssh2[\\/]lib[\\/]client\.js$/.test(path))) {
  throw new Error('ssh2 was not included in the portable host bundle')
}
if (!bundledInputs.some(path => /[\\/]bcrypt-pbkdf[\\/]index\.js$/.test(path))) {
  throw new Error('bcrypt-pbkdf was not included in the portable host bundle')
}
